[
  {
    "title":"cold rolled black annealed steel tube",
    "number":0,
    "currency":"USD",
    "priceMin":450,
    "priceMax":570,
    "priceUnit":"ton/tons",
    "moq":25,
    "moqUnit":"ton/tons",
    "supplyQuantity":6000,
    "supplyUnit":"ton/tons",
    "supplyPeriod":"month",
    "consignmentTerm":"25 days after deposit",
    "images":[],
    "kvs":[
      "steel grade":"Q195-Q235",
      "section shape":"square, rectangular, round, oval, LTZ",
      "surface treatment":"oiled",
      "Technique":"cold rolled, ERW",
      "Application":"Structure Pipe",
      "Thickness": "0.35 - 2.0 mm",
      "Standard":"GB/T 13793-1992"
    ],
    "content":"",
    "display":true
  },
  {
    "title":"cold rolled black annealed steel tube",
    "number":1,
    "currency":"USD",
    "priceMin":1,
    "priceMax":2,
    "priceUnit":"ton/tons",
    "moq":20,
    "moqUnit":"ton/tons",
    "supplyQuantity":2000,
    "supplyUnit":"ton/tons",
    "supplyPeriod":"month",
    "consignmentTerm":"",
    "images":[],
    "kvs":[],
    "content":"",
    "display":true
  },
  {
    "title":"cold rolled black annealed steel tube",
    "number":2,
    "currency":"USD",
    "priceMin":1,
    "priceMax":2,
    "priceUnit":"ton/tons",
    "moq":20,
    "moqUnit":"ton/tons",
    "supplyQuantity":2000,
    "supplyUnit":"ton/tons",
    "supplyPeriod":"month",
    "consignmentTerm":"",
    "images":[],
    "kvs":[],
    "content":"",
    "display":true
  },
  {
    "title":"cold rolled black annealed steel tube",
    "number":3,
    "currency":"USD",
    "priceMin":1,
    "priceMax":2,
    "priceUnit":"ton/tons",
    "moq":20,
    "moqUnit":"ton/tons",
    "supplyQuantity":2000,
    "supplyUnit":"ton/tons",
    "supplyPeriod":"month",
    "consignmentTerm":"",
    "images":[],
    "kvs":[],
    "content":"",
    "display":true
  },
  {
    "title":"cold rolled black annealed steel tube",
    "number":4,
    "currency":"USD",
    "priceMin":1,
    "priceMax":2,
    "priceUnit":"ton/tons",
    "moq":20,
    "moqUnit":"ton/tons",
    "supplyQuantity":2000,
    "supplyUnit":"ton/tons",
    "supplyPeriod":"month",
    "consignmentTerm":"",
    "images":[],
    "kvs":[],
    "content":"",
    "display":true
  },
  {
    "title":"cold rolled black annealed steel tube",
    "number":5,
    "currency":"USD",
    "priceMin":1,
    "priceMax":2,
    "priceUnit":"ton/tons",
    "moq":20,
    "moqUnit":"ton/tons",
    "supplyQuantity":2000,
    "supplyUnit":"ton/tons",
    "supplyPeriod":"month",
    "consignmentTerm":"",
    "images":[],
    "kvs":[],
    "content":"",
    "display":true
  }
]
